import { NestFactory } from '@nestjs/core';
import { AppModule } from './app.module';
import { ValidationPipe } from '@nestjs/common';
import { SwaggerModule, DocumentBuilder } from '@nestjs/swagger';
import { ExpressAdapter } from '@nestjs/platform-express';
import { WinstonLogger } from './common/logging/winston.logger';
import { SentryService } from './common/logging/sentry.service';
import { GlobalExceptionFilter } from './common/filters/global-exception.filter';

async function bootstrap() {
  const app = await NestFactory.create(AppModule, new ExpressAdapter(), {
    bufferLogs: true,
  });

  const winstonLogger = app.get(WinstonLogger);
  app.useLogger(winstonLogger);

  const sentryService = app.get(SentryService);
  app.useGlobalFilters(new GlobalExceptionFilter(sentryService));

  // Enforce rigid secure validation policies
  app.useGlobalPipes(
    new ValidationPipe({
      whitelist: true,
      transform: true,
      forbidNonWhitelisted: true,
    }),
  );

  // Configure CORS for multi-tenant web portals and cross-platform clients
  app.enableCors({
    origin: '*',
    methods: 'GET,HEAD,PUT,PATCH,POST,DELETE,OPTIONS',
    credentials: true,
  });

  // Swagger Documentation Setup
  const config = new DocumentBuilder()
    .setTitle('Surya Credit Solutions B2B API Suite')
    .setDescription(
      'Multi-tenant financial gateway for Distributors, Retailers, and Customers. ' +
        'Manages double-entry ledgers, dynamic credit limits, secure KYC onboards, and B2B orders.',
    )
    .setVersion('2.4.1')
    .addBearerAuth(
      {
        type: 'http',
        scheme: 'bearer',
        bearerFormat: 'JWT',
        name: 'JWT',
        description: 'Enter your authorization token generated by signing in',
        in: 'header',
      },
      'JWT-auth',
    )
    .build();

  const document = SwaggerModule.createDocument(app, config);
  SwaggerModule.setup('api/docs', app, document);

  const port = process.env.PORT || 3000;
  await app.listen(port);
  winstonLogger.log(`Surya FinTech Engine running on port: ${port}`, 'Bootstrap');
  winstonLogger.log(`Interactive API Specs available at: http://localhost:${port}/api/docs`, 'Bootstrap');
}
bootstrap();
