package com.example.ui.screens

import androidx.compose.runtime.Composable
import androidx.compose.runtime.collectAsState
import androidx.compose.runtime.getValue
import com.example.ui.AppViewModel

object Localization {
    private val translations = mapOf(
        "en" to mapOf(
            "app_settings" to "App Settings",
            "visual_theme" to "Visual Theme Configuration",
            "system" to "System",
            "light" to "Light",
            "dark" to "Dark",
            "security_admin" to "Security & Admin",
            "reload_wallet" to "RELOAD MASTER WALLET",
            "sign_out" to "SIGN OUT & LOCK PANEL",
            "raise_ticket" to "Raise a Technical Support Ticket",
            "toll_free" to "Toll Free Direct",
            "whatsapp_live" to "WhatsApp Live",
            "home" to "Home",
            "services" to "Services",
            "procure" to "Procure",
            "ai_copilot" to "AI Copilot",
            "more" to "More",
            "main_wallet" to "Main Wallet",
            "credit_limit" to "Credit Limit",
            "used_credit" to "Used Credit",
            "commission_earned" to "Commission Earned",
            "cashback_earned" to "Cashback Earned",
            "save_preferences" to "Save Custom Preferences",
            "language_selection" to "Language Selection",
            "offline_status" to "Offline Storage Sync Status",
            "sync_now" to "SYNC OFFLINE DATA NOW",
            "all_synced" to "All offline records are fully synchronized."
        ),
        "hi" to mapOf(
            "app_settings" to "ऐप सेटिंग्स",
            "visual_theme" to "दृश्य थीम कॉन्फ़िगरेशन",
            "system" to "सिस्टम",
            "light" to "लाइट",
            "dark" to "डार्क",
            "security_admin" to "सुरक्षा और व्यवस्थापक",
            "reload_wallet" to "मास्टर वॉलेट रीलोड करें",
            "sign_out" to "साइन आउट और लॉक पैनल",
            "raise_ticket" to "तकनीकी सहायता टिकट जारी करें",
            "toll_free" to "टोल फ्री डायरेक्ट",
            "whatsapp_live" to "व्हाट्सएप लाइव",
            "home" to "होम",
            "services" to "सेवाएं",
            "procure" to "खरीदें",
            "ai_copilot" to "एआई कोपायलट",
            "more" to "अधिक",
            "main_wallet" to "मुख्य वॉलेट",
            "credit_limit" to "क्रेडिट सीमा",
            "used_credit" to "प्रयुक्त क्रेडिट",
            "commission_earned" to "अर्जित कमीशन",
            "cashback_earned" to "अर्जित कैशबैक",
            "save_preferences" to "कस्टम प्राथमिकताएं सहेजें",
            "language_selection" to "भाषा चयन",
            "offline_status" to "ऑफ़लाइन संग्रहण सिंक स्थिति",
            "sync_now" to "ऑफ़लाइन डेटा अभी सिंक करें",
            "all_synced" to "सभी ऑफ़लाइन रिकॉर्ड पूरी तरह से सिंक किए गए हैं।"
        ),
        "kn" to mapOf(
            "app_settings" to "ಅಪ್ಲಿಕೇಶನ್ ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
            "visual_theme" to "ದೃಶ್ಯ ಥೀಮ್ ಸಂರಚನೆ",
            "system" to "ಸಿಸ್ಟಮ್",
            "light" to "ಬೆಳಕು",
            "dark" to "ಕತ್ತಲೆ",
            "security_admin" to "ಭದ್ರತೆ ಮತ್ತು ನಿರ್ವಾಹಕರು",
            "reload_wallet" to "ಮಾಸ್ಟರ್ ವ್ಯಾಲೆಟ್ ಮರುಲೋಡ್ ಮಾಡಿ",
            "sign_out" to "ಸೈನ್ ಔಟ್ ಮಾಡಿ ಮತ್ತು ಲಾಕ್ ಮಾಡಿ",
            "raise_ticket" to "ತಾಂತ್ರಿಕ ಬೆಂಬಲ ಟಿಕೆಟ್ ರಚಿಸಿ",
            "toll_free" to "ಟೋಲ್ ಫ್ರೀ ಡೈರೆಕ್ಟ್",
            "whatsapp_live" to "ವಾಟ್ಸಾಪ್ ಲೈವ್",
            "home" to "ಮುಖಪುಟ",
            "services" to "ಸೇವೆಗಳು",
            "procure" to "ಖರೀದಿಸಿ",
            "ai_copilot" to "ಎಐ ಸಹಾಯಕ",
            "more" to "ಇನ್ನಷ್ಟು",
            "main_wallet" to "ಮುಖ್ಯ ವ್ಯಾಲೆಟ್",
            "credit_limit" to "ಸಾಲದ ಮಿತಿ",
            "used_credit" to "ಬಳಸಿದ ಸಾಲ",
            "commission_earned" to "ಗಳಿಸಿದ ಕಮಿಷನ್",
            "cashback_earned" to "ಗಳಿಸಿದ ಕ್ಯಾಶ್‌ಬ್ಯಾಕ್",
            "save_preferences" to "ಕಸ್ಟಮ್ ಆದ್ಯತೆಗಳನ್ನು ಉಳಿಸಿ",
            "language_selection" to "ಭಾಷೆಯ ಆಯ್ಕೆ",
            "offline_status" to "ಆಫ್‌ಲೈನ್ ಸಿಂಕ್ ಸ್ಥಿತಿ",
            "sync_now" to "ಆಫ್‌ಲೈನ್ ಡೇಟಾ ಸಿಂಕ್ ಮಾಡಿ",
            "all_synced" to "ಎಲ್ಲಾ ಆಫ್‌ಲೈನ್ ದಾಖಲೆಗಳು ಸಂಪೂರ್ಣವಾಗಿ ಸಿಂಕ್ ಆಗಿವೆ."
        ),
        "ta" to mapOf(
            "app_settings" to "பயன்பாட்டு அமைப்புகள்",
            "visual_theme" to "காட்சி தீம் உள்ளமைப்பு",
            "system" to "கணினி",
            "light" to "ஒளி",
            "dark" to "இருள்",
            "security_admin" to "பாதுகாப்பு & நிர்வாகி",
            "reload_wallet" to "மாஸ்டர் வாலட்டை மீண்டும் ஏற்றுக",
            "sign_out" to "வெளியேறி பேனலை பூட்டு",
            "raise_ticket" to "தொழில்நுட்ப ஆதரவு டிக்கெட்டை உருவாக்கு",
            "toll_free" to "இலவச அழைப்பு",
            "whatsapp_live" to "வாட்ஸ்அப் லைவ்",
            "home" to "முகப்பு",
            "services" to "சேவைகள்",
            "procure" to "கொள்முதல்",
            "ai_copilot" to "ஏஐ உதவியாளர்",
            "more" to "மேலும்",
            "main_wallet" to "முதன்மை வாலட்",
            "credit_limit" to "கடன் வரம்பு",
            "used_credit" to "பயன்படுத்தப்பட்ட கடன்",
            "commission_earned" to "ஈட்டிய கமிஷன்",
            "cashback_earned" to "ஈட்டிய கேஷ்பேக்",
            "save_preferences" to "தனிப்பயன் விருப்பங்களை சேமி",
            "language_selection" to "மொழி தேர்வு",
            "offline_status" to "ஆஃப்லைன் ஒத்திசைவு நிலை",
            "sync_now" to "ஆஃப்லைன் தரவை ஒத்திசை",
            "all_synced" to "அனைத்து ஆஃப்லைன் பதிவுகளும் ஒத்திசைக்கப்பட்டுள்ளன."
        ),
        "mr" to mapOf(
            "app_settings" to "अॅप सेटिंग्ज",
            "visual_theme" to "व्हिज्युअल थीम कॉन्फिगरेशन",
            "system" to "सिस्टम",
            "light" to "लाईट",
            "dark" to "डार्क",
            "security_admin" to "सुरक्षा आणि प्रशासक",
            "reload_wallet" to "मास्टर वॉलेट रीलोड करा",
            "sign_out" to "साइन आउट आणि लॉक पॅनेल",
            "raise_ticket" to "तांत्रिक सहाय्य तिकीट मिळवा",
            "toll_free" to "टोल फ्री डायरेक्ट",
            "whatsapp_live" to "व्हॉट्सॲप लाईव्ह",
            "home" to "होम",
            "services" to "सेवा",
            "procure" to "खरेदी",
            "ai_copilot" to "एआय कोपायलट",
            "more" to "अधिक",
            "main_wallet" to "मुख्य वॉलेट",
            "credit_limit" to "क्रेडिट मर्यादा",
            "used_credit" to "वापरलेले क्रेडिट",
            "commission_earned" to "मिळालेले कमिशन",
            "cashback_earned" to "मिळालेला कॅशबॅक",
            "save_preferences" to "कस्टम प्राधान्ये जतन करा",
            "language_selection" to "भाषा निवड",
            "offline_status" to "ऑफलाईन समक्रमण स्थिती",
            "sync_now" to "ऑफलाईन डेटा समक्रमित करा",
            "all_synced" to "सर्व ऑफलाईन रेकॉर्ड पूर्णपणे समक्रमित झाले आहेत."
        ),
        "te" to mapOf(
            "app_settings" to "యాప్ సెట్టింగ్‌లు",
            "visual_theme" to "విజువల్ థీమ్ కాన్ఫిగరేషన్",
            "system" to "సిస్టమ్",
            "light" to "లైట్",
            "dark" to "డార్క్",
            "security_admin" to "సెక్యూరిటీ & అడ్మిన్",
            "reload_wallet" to "మాస్టర్ వాలెట్ రీలోడ్ చేయండి",
            "sign_out" to "సైన్ అవుట్ & లాక్ ప్యానెల్",
            "raise_ticket" to "టెక్నికల్ సపోర్ట్ టికెట్ రేజ్ చేయండి",
            "toll_free" to "టోల్ ఫ్రీ డైరెక్ట్",
            "whatsapp_live" to "వాట్సాప్ లైవ్",
            "home" to "హోమ్",
            "services" to "సేవలు",
            "procure" to "కొనుగోలు",
            "ai_copilot" to "AI కోపైలట్",
            "more" to "మరిన్ని",
            "main_wallet" to "మెయిన్ వాలెట్",
            "credit_limit" to "క్రెడిట్ పరిమితి",
            "used_credit" to "ఉపయోగించిన క్రెడిట్",
            "commission_earned" to "కమీషన్ ఆర్జన",
            "cashback_earned" to "క్యాష్‌బ్యాక్ ఆర్జన",
            "save_preferences" to "కస్టమ్ ప్రాధాన్యతలను సేవ్ చేయండి",
            "language_selection" to "భాష ఎంపిక",
            "offline_status" to "ఆఫ్‌లైన్ సమకాలీకరణ స్థితి",
            "sync_now" to "ఆఫ్‌లైన్ డేటా సింక్ చేయండి",
            "all_synced" to "ఆఫ్‌లైన్ రికార్డులన్నీ విజయవంతంగా సింక్ అయ్యాయి."
        )
    )

    fun get(key: String, lang: String): String {
        return translations[lang]?.get(key) ?: translations["en"]?.get(key) ?: key
    }
}

@Composable
fun localized(key: String, viewModel: AppViewModel): String {
    val lang by viewModel.currentLanguage.collectAsState()
    return Localization.get(key, lang)
}
